### ISSUE TITLE
patchbay crashes - this.removeWatches is not a function

### ISSUE THREAD

**Issue by frankiebee** [Happy0/ssb-chess#53]
occasionally while playing chess patchbay will crash. here is the error message that seem relevant to this:

```
TypeError: this.removeWatches is not a function
    at Object.onremove (/Users/frankie/apps-from-others/patchbay/node_modules/ssb-chess/ui/game/gameView.js:268:12)
    at onremove (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:807:107)
    at continuation (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:783:5)
    at removeNode (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:780:3)
    at updateNode (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:618:4)
    at updateNodes (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:520:12)
    at Object.render (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:958:3)
    at run1 (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:1160:40)
    at lastUpdate (/Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:1172:5)
    at /Users/frankie/apps-from-others/patchbay/node_modules/mithril/mithril.js:1174:55
```

**Comment by frankiebee** [comment]
oh and then their are some electron errors
will hopefully find some reproduction steps for this soon

**Comment by frankiebee** [comment]
&& 
version: `"ssb-chess": "^1.9.4",`
